services:

  backend:
    build: ./backend
    container_name: napp-backend
    ports:
      - "${PORT:-5000}:5000"
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: always

  frontend:
    build: ./frontend
    container_name: napp-frontend
    ports:
      - "8000:80"
    depends_on:
      - backend
    restart: always

  mongodb:
    image: mongo:8
    container_name: napp-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  mongo-express:
    image: mongo-express:latest
    container_name: napp-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH_ENABLED: "false"
    depends_on:
      - mongodb
    restart: always

volumes:
  mongodb_data:
