kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

name: emaan-kind

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30841
        hostPort: 80
        protocol: TCP

      - containerPort: 31629
        hostPort: 443
        protocol: TCP

  - role: worker

  - role: worker
