apiVersion: v1
items:
- apiVersion: v1
  data:
    JWT_SECRET: bm90ZXM=
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"backend-secret","namespace":"notes-app"},"stringData":{"JWT_SECRET":"notes"},"type":"Opaque"}
    creationTimestamp: "2026-09-04T17:43:56Z"
    name: backend-secret
    namespace: notes-app
    resourceVersion: "923631"
    uid: 433e7c64-3ce7-485a-8ba1-6dc844ccf6fb
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
